version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hms_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: hms_frontend
    ports:
      - "5174:5174"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped